version: '3.8'
services:
  app:
    # image: "${REGISTRY_HOST}${REGISTRY_URI}:latest"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.development
    volumes:
      - .:/home/app/webapp:delegated
      - tmp:/opt/app/hyrax/tmp

  # try https://www.gitmemory.com/issue/phusion/passenger/2211/505533958
  web:
    extends: app
    command: bundle exec rails s puma -b 0.0.0.0 -p 3000
    environment:
      VIRTUAL_HOST: trinity.docker
      VIRTUAL_PORT: 3000
    depends_on:
      - redis
      - solr
      - fcrepo
      - mysql
      - workers
  
  workers:
    extends: app
    command: bundle exec sidekiq
    depends_on:
      - redis
      - solr
      - fcrepo
      - mysql
    stdin_open: true
    tty: true

  redis:
    image: redis:4
    volumes:
      - redis:/data

  mysql:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  solr:
    # image: "${REGISTRY_HOST}${REGISTRY_URI}/solr:latest"
    build:
      context: .
      dockerfile: Dockerfile.solr
    ports:
      - "8983:8983"
    volumes:
      - './solr/config:/opt/solr/server/configsets/hyraxconf'
    command:
      - sh
      - "-c"
      - "precreate-core hyrax_test /opt/solr/server/configsets/hyraxconf; solr-precreate hyrax /opt/solr/server/configsets/hyraxconf"

  fcrepo:
    image: botimer/fcrepo:4.5.1
    volumes:
      - 'fcrepo:/opt/data'
    ports:
      - "8984:8080"

volumes:
  fcrepo:
  mysql:
  redis:
  tmp:
