terms:
  - id: cartographic
    term: cartographic
  - id: notated music
    term: notated music
  - id: sound recording
    term: sound recording
  - id: sound recording-musical
    term: sound recording-musical
  - id: sound recording-nonmusical
    term: sound recording-nonmusical
  - id: still image
    term: still image
  - id: moving image
    term: moving image
  - id: text
    term: text
  - id: three dimensional object
    term: three dimensional object
  - id: software, multimedia
    term: software, multimedia
  - id: mixed material
    term: mixed material
  - id: other
    term: other
