development:
  adapter: async

demovm045:
  adapter: async

demovm099:
  adapter: async

dcdevhyrax:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: tcd_hyrax_app_3_production
