
development:
  user: <%= ENV['FEDORA_ADMIN_USER'] || 'fedoraAdmin' %>
  password: <%= ENV['FEDORA_ADMIN_PASSWORD'] || 'fedoraAdmin' %>
    #fedoraAdmin
  url: <%= ENV['FEDORA_URL'] || 'http://127.0.0.1:8080/fcrepo-webapp-4.7.5/rest' %>
  base_path: /dev

dcdevhyrax:
  user: <%= ENV['FEDORA_ADMIN_USER'] %>
  password: <%= ENV['FEDORA_ADMIN_PASSWORD'] %>
  url: http://dcdev-fedora.tcd.ie:8080/fcrepo-webapp-4.7.5/rest
  base_path: /dev

digcollhyrax01:
  user: <%= ENV['FEDORA_ADMIN_USER'] %>
  password: <%= ENV['FEDORA_ADMIN_PASSWORD'] %>
  url: http://digcoll-fedora01.tcd.ie:8080/fcrepo-webapp-4.7.5/rest
  base_path: /dev

digcollhyrax02:
  user: <%= ENV['FEDORA_ADMIN_USER'] %>
  password: <%= ENV['FEDORA_ADMIN_PASSWORD'] %>
  url: http://digcoll-fedora02.tcd.ie:8080/fcrepo-webapp-4.7.5/rest
  base_path: /dev

test:
  user: <%= ENV['FEDORA_ADMIN_USER'] %>
  password: <%= ENV['FEDORA_ADMIN_PASSWORD'] %>
  url: http://127.0.0.1:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
  #url: <%= ENV['FEDORA_URL'] || "http://127.0.0.1:#{ ENV['FCREPO_TEST_PORT'] || 8986 }/rest" %>
  base_path: /test

production:
  user: <%= ENV['FEDORA_ADMIN_USER'] %>
  password: <%= ENV['FEDORA_ADMIN_PASSWORD'] %>
  url: http://127.0.0.1:8983/fedora/rest
  base_path: /prod
