development:
  host: localhost
  port: 6379
demovm045:
  host: localhost
  port: 6379
demovm099:
  host: localhost
  port: 6379
dcdevhyrax:
  host: localhost
  port: 6379
digcollhyrax01:
  host: localhost
  port: 6379
test:
  host: localhost
  port: 6379
production:
  host: localhost
  port: 6379
