development:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: 6379
dcdevhyrax:
  host: localhost
  port: 6379
digcollhyrax01:
  host: localhost
  port: 6379
digcollhyrax02:
  host: localhost
  port: 6379
test:
  host: localhost
  port: 6379
production:
  host: localhost
  port: 6379
