# TODO : add this to .gitignore?

development:
  archivist:
    - archivist1@example.com
#    - cataloger@tcd.ie
  admin:
    - jlakes@tcd.ie
    - batchuser@example.com
    - test@example.com
    - magar@tcd.ie

dcdevhyrax:
  admin:
    - jlakes@tcd.ie
    - batchuser@example.com
    - magar@tcd.ie
    - smsutton@tcd.ie
    - arhealy@tcd.ie
    - whelangp@tcd.ie
    - doylej37@tcd.ie
    - schmidc@tcd.ie
    - laura.shanahan@tcd.ie
    - bioletts@tcd.ie

digcollhyrax01:
  admin:
    - jlakes@tcd.ie
    - batchuser@example.com
    - magar@tcd.ie
    - smsutton@tcd.ie
    - arhealy@tcd.ie
    - whelangp@tcd.ie
    - doylej37@tcd.ie
    - schmidc@tcd.ie
    - laura.shanahan@tcd.ie
    - bioletts@tcd.ie

digcollhyrax02:
  admin:
    - jlakes@tcd.ie
    - batchuser@example.com
    - magar@tcd.ie
    - smsutton@tcd.ie
    - arhealy@tcd.ie
    - whelangp@tcd.ie
    - doylej37@tcd.ie
    - schmidc@tcd.ie
    - laura.shanahan@tcd.ie
    - bioletts@tcd.ie

test:
  admin:
      - jlakes@tcd.ie
      - test@example.com
      - batchuser@example.com
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
#    - cataloger@tcd.ie
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com

production:
  # Add roles for users here.
