# NOTE: rails_env doesn't work here


fixity_audit:
  cron: "05 01 * * 6"
  class: FixityAuditJob
  rails_env: development
  queue: fixity

fixity_audit:
  cron: "10 01 * * 6"
  class: FixityAuditJob
  rails_env: dcdevhyrax
  queue: fixity

fixity_audit:
  cron: "15 01 * * 6"
  class: FixityAuditJob
  rails_env: digcollhyrax01
  queue: fixity

send_doi_to_sierra:
  cron: "15 02 * * 6"
  class: SendDoiToSierraJob
  queue: export
