# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base


  #self.indexer = FileSetIndexer

  property :provenance, predicate: ::RDF::URI.new('https://digitalcollections.tcd.ie/app/assets/local_vocabulary.html#provenance') do |index|
    index.as :stored_searchable
  end

  include ::Hyrax::FileSetBehavior
end
