# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base

  require 'exifr/jpeg'
  #self.indexer = FileSetIndexer

  property :camera_model, predicate: ::RDF::Vocab::EXIF.model, multiple: false do |index|
    index.as :stored_searchable
  end

  property :camera_make, predicate: ::RDF::Vocab::EXIF.make, multiple: false do |index|
    index.as :stored_searchable
  end

  property :date_taken, predicate: ::RDF::Vocab::EXIF.dateTimeOriginal, multiple: false do |index|
    index.as :stored_searchable
  end

  property :exposure_time, predicate: ::RDF::Vocab::EXIF.exposureTime, multiple: false do |index|
    index.as :stored_searchable
  end

  property :f_number, predicate: ::RDF::Vocab::EXIF.apertureValue, multiple: false do |index|
    index.as :stored_searchable
  end

  property :iso_speed_rating, predicate: ::RDF::Vocab::EXIF.isoSpeedRatings, multiple: false do |index|
    index.as :stored_searchable
  end

  property :flash, predicate: ::RDF::Vocab::EXIF.flash, multiple: false do |index|
    index.as :stored_searchable
  end

  property :exposure_program, predicate: ::RDF::Vocab::EXIF.exposureIndex, multiple: false do |index|
    index.as :stored_searchable
  end

  property :focal_length, predicate: ::RDF::Vocab::EXIF.focalLength, multiple: false do |index|
    index.as :stored_searchable
  end

  property :software, predicate: ::RDF::Vocab::EXIF.software, multiple: false do |index|
    index.as :stored_searchable
  end

  property :fedora_sha1, predicate: ::RDF::URI.new('https://digitalcollections.tcd.ie/app/assets/local_vocabulary.html#fedora_sha1'), multiple: false do |index|
    index.as :stored_searchable
  end

  include ::Hyrax::FileSetBehavior
end
