# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_hyrax
    #      MYSQL_USER: travis
    #      MYSQL_PASSWORD: Pa$$w0rd
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        ruby-version: ['2.5']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: sudo /etc/init.d/mysql start
    - run: cp ./config/.github.database.yml ./config/database.yml
    - run: cp ./config/.travis.secrets.yml ./config/secrets.yml

    - run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS test_hyrax;

    - name: Set up app
      run: RAILS_ENV=test bundle exec rails db:create

    #- name: Create test database
    #  run: mysql  -uroot -proot -e "create database test_hyrax; grant all privileges on *.* to 'hyrax'@'%'"
    #- run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS test_hyrax character set utf8mb4 collate utf8mb4_unicode_ci;'
    #- run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e "CREATE USER 'travis'@'localhost';" # IDENTIFIED BY 'Pa$$w0rd';"
    #- run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e "GRANT ALL PRIVILEGES ON test_hyrax.* TO 'travis'@'localhost';"
    - name: Run tests
      run: bundle exec rspec
